server:
  port: 8088

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

authorization-server: http://127.0.0.1:9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${authorization-server}/oauth2/jwks"
#          issuer-uri: http://127.0.0.1:9000
